### ISSUE TITLE
explore d3

### ISSUE THREAD

**Issue by teddybeaker** [smartvoteCH/dataliteracy#6]
- Pie-Chart / Balkendiagramm
- Säulen- vs. Kuchendiagramme: https://twitter.com/MaxCRoser/status/857389434756505600 und hier noch die Grafiken: https://commons.wikimedia.org/wiki/File:Piecharts.svg

**Comment by smartvoteCH** [comment]
Liniendiagramm

**Comment by smartvoteCH** [comment]
won't do
